version: '3'
services:
  nwn:
    image: nwnxee/unified:latest
    container_name: nwn_server
    env_file:
      - nwnx.env
    environment:
      - NWN_MODULE=customgiga
      - NWN_MAXCLIENTS=10
      - NWN_SERVERNAME=My Server
      - NWN_PORT=5121
    volumes:
      - D:\Documents\Neverwinter Nights\modules:/nwn/home/modules
    ports:
      - "30000:5121/udp"